id: I674A8F69
legacy_id: P006919
ocr_import_info:
  bdrc_scan_id: W3CN4347
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T16:24:21'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:26:28.120253+00:00'
last_modified: 2022-09-03 22:26:42.735674
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4347
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4347
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དུས་ཀྱི་འཁོར་ལོའི་སྤྱི་དོན། ༼དེབ་གཉིས་པ།༽
statistics:
  ocr_word_mean_confidence_index: 0.6917964865164183
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I3CN4564:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4564
      total_pages: 380
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4564.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.6917964865164183
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
