id: P006919
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4347
  title: དུས་ཀྱི་འཁོར་ལོའི་སྤྱི་དོན། ༼དེབ་གཉིས་པ།༽
  author: ''
  volumes:
    60183075bb2d40ea8322279dd809785d:
      image_group_id: I3CN4564
      title: ''
      volume_number: 1
      total_pages: 380
      base_file: v001.txt
