id: P006919
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:30:42.943596
source_metadata:
  id: bdr:W3CN4347
  title: དུས་ཀྱི་འཁོར་ལོའི་སྤྱི་དོན། ༼དེབ་གཉིས་པ།༽
  author: ''
  volumes:
    60183075bb2d40ea8322279dd809785d:
      image_group_id: I3CN4564
      title: ''
      volume_number: 1
      total_pages: 380
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
